name: Docker

on:
  push:
    branches:
    - master
    tags:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false
      matrix:
        version:
        - "25.0.3"
        - "26.0.0"
        flavor:
        - nvidia
        include:
        - version: "25.0.3"
          version_major: "25"
        - version: "26.0.0"
          version_major: "26"
        - flavor: nvidia
          suffix: -nvidia

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure
      id: config
      uses: actions/github-script@v7
      env:
        GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
      with:
        script: |
          const os = require('os')

          core.exportVariable('NPROC', os.cpus().length * 2)
          core.setOutput('NPROC', os.cpus().length * 2)

          core.setOutput('image-owner', process.env.GITHUB_REPOSITORY_OWNER)
          core.setOutput('image-name', process.env.GITHUB_REPOSITORY_NAME.replace(/^docker-/, ''))
    
    - name: Setup - Setup buildx
      uses: docker/setup-buildx-action@v3

    - name: Setup - Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Setup - Github Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Setup - Docker image metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |-
          ${{ steps.config.outputs.image-owner }}/${{ steps.config.outputs.image-name }}
          ghcr.io/${{ steps.config.outputs.image-owner }}/${{ steps.config.outputs.image-name }}
        flavor: |-
          latest=false
          suffix=${{ matrix.suffix }}
        tags: |-
          type=semver,pattern={{major}}.{{minor}},value=${{ matrix.version }}
          type=semver,pattern={{major}}.{{minor}}.{{patch}},value=${{ matrix.version }}

    - name: Build
      uses: docker/build-push-action@v5
      id: build
      with:
        context: ${{ matrix.version_major }}/${{ matrix.flavor }}
        build-args: |
          version=${{ matrix.version }}
          version_major=${{ matrix.version_major }}
          nvidia_container_toolkit=${{ matrix.nvidia_container_toolkit }}
        push: true
        labels: ${{ steps.meta.outputs.labels }}
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
